"""EV tree search over attack programs (analog of score_golf.uct.Searcher).

Structure mirrors score_golf: a beam of parent nodes selected by a PUCT score,
each expanded with structural mutations + LLM proposals, children evaluated by
the oracle, reward back-propagated. Two differences reflect the JED objective:

  * reward is **risk-adjusted raw EV per replay second**, not code shortening;
  * a **Go-Explore archive** keyed by scoring-cell keeps every novel cell as a
    frontier (diversity is worth +2 raw each), so the search farms breadth as
    well as depth.

The output is the material the submission needs: a ranked table of high-EV arms,
the set of discovered cells, and the raw findings for portfolio packing.
"""

from __future__ import annotations

import math
import time
from dataclasses import dataclass, field
from typing import Callable

from engine import generator, oracle, repair, scoring
from engine.contracts import AttackProgram, AttackReport
from engine.deduper import fingerprints
from engine.program import render
from engine.sandbox import AttackSandbox


@dataclass
class Node:
    program: AttackProgram
    arm: scoring.EVArmStats
    reports: list[AttackReport]
    visits: int = 0
    value: float = 0.0             # cumulative reward (EV/s), backpropagated up the tree
    feedback: list[str] = field(default_factory=list)
    expanded: bool = False
    parent: "Node | None" = None   # tree edge, for real UCB backpropagation
    depth: int = 0
    go_explored: bool = False

    @property
    def q(self) -> float:
        return self.value / max(1, self.visits)

    def backprop(self, reward: float) -> None:
        """Propagate a child's reward up the ancestor chain (real tree backup)."""
        node: "Node | None" = self
        while node is not None:
            node.visits += 1
            node.value += reward
            node = node.parent


@dataclass
class SearchStats:
    steps: int = 0
    oracle_calls: int = 0
    llm_calls: int = 0
    programs_seen: int = 0
    positive_arms: int = 0
    cells: int = 0
    duration_s: float = 0.0
    prefix_reuse: int = 0          # replays that restored a cached prefix snapshot
    prefix_saved_msgs: int = 0     # total leading messages served from cache (skipped model turns)
    repair_from_break: int = 0     # programs generated by repair-from-break expansion
    llm_programs: int = 0          # attack programs proposed by the LLM strategist
    go_explore_expansions: int = 0 # continuations explored from archived scored states
    cold_resamples: int = 0        # VOI cold re-validations of promising arms
    cold_validated_arms: int = 0   # arms confirmed on an independent cold replay
    # LLM telemetry (is the strategist worth its ~150 s/call?)
    llm_wall_s: float = 0.0
    llm_parse_fail: int = 0        # LLM calls that returned 0 valid programs
    llm_downstream_eligible: int = 0   # LLM programs that became eligible arms
    llm_downstream_ev: float = 0.0     # Σ severity EV/s of LLM-origin eligible arms


class Searcher:
    def __init__(
        self,
        *,
        sandbox: AttackSandbox,
        seeds: list[AttackProgram],
        time_budget_s: float = 120.0,
        max_steps: int = 10_000,
        trials_per_program: int = 2,
        beam: int = 6,
        mutations_per_expand: int = 6,
        llm_per_expand: int = 0,          # 0 disables LLM (still runs on mutation)
        llm_every: int = 2,               # LLM phase runs every N search steps (it is slow)
        llm_top_m: int = 3,               # LLM-mutate the top-M nodes concurrently
        llm_cold_start: int = 0,          # design this many programs FROM SCRATCH at init
        llm_wall_cap: float = 0.15,       # cap the LLM's share of wall-clock (it is slow)
        go_explore: bool = True,          # return to archived cells and explore continuations
        go_explore_every: int = 2,        # run the Go-Explore phase every N steps
        resample_every: int = 3,          # VOI cold-resample phase every N steps (0 = off)
        resample_top: int = 4,            # how many uncertain arms to cold-resample per phase
        cold_target: int = 2,             # cold samples an arm needs to be "validated"
        puct_c: float = 1.4,
        strategy_bank: list[dict] | None = None,
        llm_model: str | None = None,
        on_event: Callable[[dict], None] | None = None,
        checkpoint_cb: Callable[["Searcher"], None] | None = None,
        checkpoint_every_s: float = 120.0,
    ) -> None:
        self.sb = sandbox
        self.time_budget_s = float(time_budget_s)
        self.max_steps = int(max_steps)
        self.trials = max(1, int(trials_per_program))
        self.beam = max(1, int(beam))
        self.mut_k = int(mutations_per_expand)
        self.llm_k = int(llm_per_expand)
        self.llm_every = max(1, int(llm_every))
        self.llm_top_m = max(1, int(llm_top_m))
        self.llm_cold_start = max(0, int(llm_cold_start))
        self.llm_wall_cap = float(llm_wall_cap)
        self.go_explore = bool(go_explore)
        self.go_explore_every = max(1, int(go_explore_every))
        self.resample_every = max(0, int(resample_every))
        self.resample_top = max(1, int(resample_top))
        self.cold_target = max(1, int(cold_target))
        self.puct_c = float(puct_c)
        self.strategy_bank = strategy_bank or generator.load_strategy_bank()
        self.llm_model = llm_model
        self.on_event = on_event or (lambda e: None)
        self.checkpoint_cb = checkpoint_cb
        self.checkpoint_every_s = float(checkpoint_every_s)
        self._last_ckpt = time.perf_counter()

        self.nodes: dict[str, Node] = {}          # text_fp -> Node
        self.seen_fps: set[tuple[str, str]] = set()
        self.archive_cells: dict[str, str] = {}   # cell_hash -> text_fp that first found it
        self.all_reports: list[AttackReport] = []
        self.stats = SearchStats()
        self._nonce = 10_000
        self._seed_programs = seeds

    # -- evaluation -----------------------------------------------------------

    def _next_nonce(self) -> int:
        self._nonce += 1
        return self._nonce

    def _evaluate(self, program: AttackProgram, *, parent: Node | None = None) -> Node | None:
        rendered = render(program, self._nonce + 1)
        fp = fingerprints(program, rendered)
        if fp in self.seen_fps:
            return None
        self.seen_fps.add(fp)

        reports: list[AttackReport] = []
        for _ in range(self.trials):
            rep = oracle.evaluate(program, self.sb, nonce=self._next_nonce())
            self.stats.oracle_calls += 1
            reports.append(rep)
            self.all_reports.append(rep)
        arm = scoring.compute_arm(
            reports, family=program.family, mechanism=program.mechanism, max_tool_hops=program.max_tool_hops
        )
        self.stats.programs_seen += 1
        node = Node(program=program, arm=arm, reports=reports, parent=parent,
                    depth=(parent.depth + 1 if parent else 0))
        node.feedback = repair.build_trace_feedback(reports[-1])
        self.nodes[fp[1]] = node

        # Go-Explore archive: register novel scoring cells, remembering the node
        # (and thus the snapshot state) that first reached each cell so we can
        # RETURN to it and explore continuations from there.
        for rep in reports:
            if rep.solved and rep.cell_hash and rep.cell_hash not in self.archive_cells:
                self.archive_cells[rep.cell_hash] = fp[1]
        if arm.eligible:
            self.stats.positive_arms += 1
        self.stats.cells = len(self.archive_cells)
        self.on_event({
            "t": "eval", "program": program.name, "family": program.family,
            "sev_ev_per_s": round(arm.severity_ev_per_s, 4), "n_cells": len(arm.cell_hashes),
            "stop": reports[-1].stop_reason,
        })
        return node

    # -- selection ------------------------------------------------------------

    def _select_parents(self) -> list[Node]:
        pool = list(self.nodes.values())
        if not pool:
            return []
        total_visits = max(2, sum(n.visits for n in pool) + 1)
        log_n = math.log(total_visits)

        def ucb(n: Node) -> float:
            # exploitation = backed-up Q (value/visits over the subtree), blended
            # with the arm's own EV so unexpanded-but-high-EV nodes rank well.
            q = 0.7 * n.q + 0.3 * (n.arm.projected_norm + 0.25 * n.arm.severity_ev_per_s)
            # exploration = the canonical UCB1 term c*sqrt(ln N / n_i)
            explore = self.puct_c * math.sqrt(log_n / max(1, n.visits))
            novelty = 0.1 * len(n.arm.cell_hashes)
            rep = n.reports[-1] if n.reports else None
            repairable = (
                0.6 if (rep is not None and rep.break_index is not None
                        and len(n.program.steps) > 1 and not n.expanded) else 0.0
            )
            return q + explore + novelty + repairable

        pool.sort(key=ucb, reverse=True)
        return pool[: self.beam]

    # -- expansion ------------------------------------------------------------

    def _expand(self, node: Node) -> list[AttackProgram]:
        """Fast, LLM-free expansion: DSL mutations + repair-from-break.

        The LLM is applied separately as a first-class, parallel phase over the
        whole beam (see _llm_phase), because it is the *design* engine, not a
        template. Mutations here mainly farm/refine methods the LLM discovers.
        """
        node.expanded = True  # visit accounting is handled by backprop
        proposals: list[AttackProgram] = []
        if self.mut_k > 0:
            proposals.extend(
                generator.propose_mutations(node.program, feedback=node.feedback, budget=self.mut_k)
            )
        brk = node.reports[-1].break_index if node.reports else None
        if brk is not None and len(node.program.steps) > 1:
            repairs = generator.propose_repair_from_break(
                node.program, brk, feedback=node.feedback, budget=max(3, self.mut_k)
            )
            self.stats.repair_from_break += len(repairs)
            proposals.extend(repairs)
        return proposals

    def _llm_phase(self) -> list[AttackProgram]:
        """Two-role LLM phase: TRACE CRITIC diagnoses the top-M nodes' FULL traces,
        then the ATTACK DESIGNER invents new programs from that diagnosis.

        The critic sees the complete trace evidence (messages, every tool call +
        args + denials + which predicates missing) — not a thin summary — so it can
        truly diagnose; the designer works from the distilled diagnosis, keeping
        each call's burden low. This is the notebook's critic/designer split, scoped
        to the two roles that actually drive high-EV discovery.
        """
        pool = [n for n in self.nodes.values()]
        # prefer the most informative nodes: scored ones AND blocked/refused ones
        pool.sort(
            key=lambda n: (n.arm.severity_ev_per_s + 0.3 * len(n.arm.cell_hashes)
                           + (0.5 if (n.reports and (n.reports[-1].denied or n.reports[-1].refused)) else 0.0)),
            reverse=True,
        )
        targets = pool[: max(1, self.llm_top_m)]
        node_reports = [(t.program.name, t.reports[-1]) for t in targets if t.reports]
        self.on_event({"t": "llm_call", "step": self.stats.steps,
                       "on": [t.program.name for t in targets], "mode": "critic+designer"})
        _lt = time.perf_counter()
        try:
            out, meta = generator.propose_llm_roles(
                node_reports, strategy_bank=self.strategy_bank, n=max(self.llm_k * self.llm_top_m, 4),
                model=self.llm_model,
            )
        except Exception as exc:
            self.stats.llm_wall_s += time.perf_counter() - _lt
            self.on_event({"t": "llm_err", "step": self.stats.steps, "err": str(exc)[:120]})
            return []
        self.stats.llm_wall_s += time.perf_counter() - _lt
        self.stats.llm_calls += int(meta.get("calls", 0) or 0)
        if meta.get("diagnosis"):
            self.on_event({"t": "llm_diagnosis", "step": self.stats.steps, "text": meta["diagnosis"][:400]})
        if not out:
            self.stats.llm_parse_fail += 1
        self.stats.llm_programs += len(out)
        self.on_event({"t": "llm_done", "step": self.stats.steps,
                       "produced": len(out), "names": [p.name for p in out][:6]})
        return out

    def _go_explore_phase(self) -> list[tuple[AttackProgram, Node]]:
        """Return to archived SCORED states and explore continuations from them.

        Frontier = the nodes that first reached a scoring cell. We pick the most
        promising un-explored ones, and build continuation programs whose fixed
        prefix is that node's EXACT scored messages — so the snapshot prefix cache
        restores the reached state and we only pay for the appended action.
        """
        frontier_fps = set(self.archive_cells.values())
        frontier = [self.nodes[f] for f in frontier_fps if f in self.nodes]
        frontier = [n for n in frontier if not n.go_explored and n.arm.eligible and n.arm.messages]
        if not frontier:
            return []
        frontier.sort(
            key=lambda n: n.arm.severity_ev_per_s + 0.3 * len(n.arm.cell_hashes) - 0.2 * n.visits,
            reverse=True,
        )
        out: list[tuple[AttackProgram, Node]] = []
        for n in frontier[: self.llm_top_m]:
            n.go_explored = True
            for cont in generator.propose_continuations(n.arm.messages, budget=4):
                out.append((cont, n))
        if out:
            self.on_event({"t": "go_explore", "step": self.stats.steps, "from": len(frontier[: self.llm_top_m]),
                           "continuations": len(out)})
        return out

    def _resample_phase(self) -> None:
        """VOI: add INDEPENDENT cold samples to the arms where it matters most.

        Instead of a fixed N trials for every program (which spends the same
        compute on obvious losers and known winners), we screen once and then
        cold-resample only the eligible arms that are (a) not yet cold-validated
        or (b) still uncertain — weighted by EV, so extra replays go where they
        could actually change the final ranking.
        """
        cands = [
            n for n in self.nodes.values()
            if n.arm.eligible and n.arm.n_cold < self.cold_target
        ]
        if not cands:
            return
        cands.sort(key=lambda n: n.arm.severity_ev_per_s * (0.5 + n.arm.uncertainty), reverse=True)
        run_t0 = getattr(self, "_run_t0", time.perf_counter())
        for n in cands[: self.resample_top]:
            # deadline guard: don't start a cold replay we can't finish before budget.
            # Uses MEASURED wall time (≈0 on the free deterministic env; seconds on a
            # GGUF target), with a small floor — not the modeled EV denominator.
            est = max(n.arm.mean_wall_s * 1.3, 0.02)
            if (time.perf_counter() - run_t0) + est >= self.time_budget_s:
                break
            rep = oracle.evaluate(n.program, self.sb, nonce=self._next_nonce(), use_cache=False)  # cold
            self.stats.oracle_calls += 1
            self.stats.cold_resamples += 1
            self.all_reports.append(rep)
            n.reports.append(rep)
            n.arm = scoring.compute_arm(
                n.reports, family=n.program.family, mechanism=n.program.mechanism,
                max_tool_hops=n.program.max_tool_hops,
            )
        self.stats.cold_validated_arms = sum(1 for n in self.nodes.values() if n.arm.cold_validated)

    # -- main loop ------------------------------------------------------------

    def run(self) -> dict:
        t0 = time.perf_counter()
        self._run_t0 = t0

        # Cold start: let the LLM DESIGN attacks from scratch (the "from 0" mode).
        # Runs even with an empty seed bank, so the search need not start from a
        # pre-baked point. Concurrent calls keep the wall cost near one call.
        if self.llm_cold_start > 0 and self.llm_k > 0:
            self.on_event({"t": "cold_start", "n": self.llm_cold_start})
            try:
                _ct = time.perf_counter()
                cold = generator.propose_llm_cold(
                    n_programs=self.llm_cold_start, strategy_bank=self.strategy_bank, model=self.llm_model
                )
                self.stats.llm_wall_s += time.perf_counter() - _ct
                meta = generator.get_last_llm_meta()
                self.stats.llm_calls += int(meta.get("calls", 0) or 0)
                self.stats.llm_programs += len(cold)
                if not cold:
                    self.stats.llm_parse_fail += 1
                self.on_event({"t": "cold_done", "produced": len(cold), "names": [p.name for p in cold][:8]})
                for p in cold:
                    if time.perf_counter() - t0 > self.time_budget_s:
                        break
                    self._evaluate(p)
            except Exception as exc:
                self.on_event({"t": "cold_err", "err": str(exc)[:120]})

        for p in self._seed_programs:
            if time.perf_counter() - t0 > self.time_budget_s:
                break
            self._evaluate(p)

        while (time.perf_counter() - t0) < self.time_budget_s and self.stats.steps < self.max_steps:
            self.stats.steps += 1
            parents = self._select_parents()
            if not parents and not self.nodes:
                break
            improved = False

            # fast, LLM-free expansion (mutations + repair) over the beam, with
            # real tree backup of the child reward up the ancestor chain.
            for parent in parents:
                if (time.perf_counter() - t0) >= self.time_budget_s:
                    break
                for child_prog in self._expand(parent):
                    if (time.perf_counter() - t0) >= self.time_budget_s:
                        break
                    child = self._evaluate(child_prog, parent=parent)
                    if child is None:
                        continue
                    child.backprop(child.arm.projected_norm + 0.5 * len(child.arm.cell_hashes))
                    if child.arm.eligible:
                        improved = True

            # Go-Explore phase: return to archived scored states, explore continuations
            if self.go_explore and (self.stats.steps % self.go_explore_every == 0) and (time.perf_counter() - t0) < self.time_budget_s:
                for cont_prog, anchor in self._go_explore_phase():
                    if (time.perf_counter() - t0) >= self.time_budget_s:
                        break
                    child = self._evaluate(cont_prog, parent=anchor)
                    if child is None:
                        continue
                    self.stats.go_explore_expansions += 1
                    child.backprop(child.arm.projected_norm + 0.5 * len(child.arm.cell_hashes))
                    if child.arm.eligible:
                        improved = True

            # VOI cold-resample phase: independently re-validate the arms that matter
            if self.resample_every and (self.stats.steps % self.resample_every == 0) and (time.perf_counter() - t0) < self.time_budget_s:
                self._resample_phase()

            # first-class LLM phase: design/improve the top-M nodes concurrently.
            # Gated by a wall-share cap so the slow strategist can't starve the fast
            # search (and can be throttled if it proves unproductive).
            elapsed = time.perf_counter() - t0
            if (self.llm_k > 0 and (self.stats.steps % self.llm_every == 0)
                    and self.stats.llm_wall_s < self.llm_wall_cap * max(1.0, elapsed)
                    and elapsed < self.time_budget_s):
                for child_prog in self._llm_phase():
                    child = self._evaluate(child_prog)
                    if child is not None and child.arm.eligible:
                        improved = True

            self.on_event({"t": "step", "step": self.stats.steps, "arms": len(self.nodes),
                           "positive": self.stats.positive_arms, "cells": self.stats.cells})
            # periodic checkpoint so a long run's progress survives a runtime/tunnel
            # drop — the callback distills+saves the current prior mid-run.
            if self.checkpoint_cb is not None and (time.perf_counter() - self._last_ckpt) >= self.checkpoint_every_s:
                self._last_ckpt = time.perf_counter()
                try:
                    self.checkpoint_cb(self)
                except Exception:
                    pass
            # only early-stop when there is truly nothing to work with (no LLM in play)
            if (self.llm_k == 0 and not improved and self.stats.steps > 12
                    and not any(n.arm.eligible for n in self.nodes.values())):
                break

        self.stats.duration_s = time.perf_counter() - t0
        self.stats.prefix_reuse = getattr(self.sb, "reuse_events", 0)
        self.stats.prefix_saved_msgs = getattr(self.sb, "reuse_saved_messages", 0)
        # LLM downstream productivity: how much EV the strategist's programs earned
        for n in self.nodes.values():
            if n.program.source in ("llm", "llm_cold") and n.arm.eligible:
                self.stats.llm_downstream_eligible += 1
                self.stats.llm_downstream_ev += n.arm.severity_ev_per_s
        self.stats.cold_validated_arms = sum(1 for n in self.nodes.values() if n.arm.cold_validated)
        return self.current_result()

    def current_result(self) -> dict:
        """The result dict from the CURRENT node set — callable mid-run for checkpoints."""
        arms = sorted(
            (n.arm for n in self.nodes.values()),
            key=lambda a: (a.projected_norm, a.risk_adjusted_ev_per_s),
            reverse=True,
        )
        return {
            "arms": arms,
            "nodes": self.nodes,
            "archive_cells": dict(self.archive_cells),
            "all_reports": self.all_reports,
            "stats": self.stats,
        }
